CC ?= gcc
CFLAGS ?= -Wall -Wextra -std=c11 -g -D_POSIX_C_SOURCE=200809L
OUTDIR ?= build_out

.PHONY: test clean

$(OUTDIR):
	mkdir -p $(OUTDIR)

$(OUTDIR)/smoke_eth: tests/smoke_eth.c src/eth.c include/dephy_eth/eth.h | $(OUTDIR)
	$(CC) $(CFLAGS) -Iinclude tests/smoke_eth.c src/eth.c -o $@

test: $(OUTDIR)/smoke_eth
	$<

clean:
	rm -rf $(OUTDIR)

